pndaproject/platform-salt

salt/cdh/files/cm_setup.py

cm_setup.py now waits for cloudera manager to come up when connecting.
Recent changes to set the username and password had stopped this from
waiting correctly.

PNDA-1933. CM setup waits on cloudera manager being available.

---

salt/cdh/cloudera-manager.sls

This is vulnerable to man in the middle attack, and since cloudera
offer https, there is no reason to use http.
Fix CVE-2016-1000036

Do not use http download for cloudera manager

---

salt/_modules/pnda.py

Use private IP addresses for AWS hosts in pnda.ip_addresses so that
PNDA can be launched in a private network.
PNDA-1976

Use private IP address for AWS hosts

---

salt/jupyter/files/PNDA minimal notebook.ipynb
salt/jupyter/init.sls

In particular, it uses '%matplolib notebook' instead of '%matplotlib
inline'; it make plots nicer in notebooks.
It also emphasis the fact that '%matplotlib ...' must be executed before
'import matplotlib ...' if you want plots to be displayed.
PNDA-1914

Add a simple minimal notebook to explain basic usage

---

pillar/services.sls
salt/zookeeper/files/templates/environment.tpl
salt/zookeeper/files/templates/zoo.cfg.tpl
salt/zookeeper/files/templates/zookeeper.init.conf.tpl
salt/zookeeper/init.sls

Do not rely on apt for installing zookeeper and now default version is 3.4.6
PNDA-2016

 Update zookeeper in order to be able to install a dedicated version

---

salt/console-backend/data-logger.sls
salt/console-backend/templates/backend_nodejs_app.conf.tpl

A new 'no_console_log' template variable was introduced to enable or
disable console logging in upstart logs.
PNDA-2009

Tell upstart to not log console output of data-logger

---

salt/cdh/files/cm_setup.py

Re-raise exceptions from cm_setup so that the process exits with a
non-zero exit code when an error occurs in hadoop setup.
PNDA-2022.

Re-raise exceptions from cm_setup

---

salt/graphite/init.sls

python-pip is included as a dependency to ensure the correct version of pip is used when installing graphite.
PNDA-2143

Include python-pip in graphite sls

---

salt/graphite/init.sls

cariocffi 0.7 was seen to fail to install
PNDA-2305

Pin version of cariocffi and graphite-api

---

salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_standard.py.tpl
salt/logserver/logshipper.sls
salt/logserver/logshipper_files/open_yarn_log_permissions.sh
salt/logserver/logshipper_templates/shipper.conf.tpl

To avoid missing logs for short lived yarn jobs, check for log files
every 5 seconds.
PNDA-2215.

PNDA-2215: Check for yarn logs more frequently

---

salt/cdh/templates/hue-user-setup.sh.tpl

Explicit check on whether the user exists rather than relying on an
error being thrown and caught if it already exists.
PNDA-2302

Check if hue user exists before creating it

---

salt/orchestrate/pnda.sls
salt/reboot/files/pnda_restart.py
salt/reboot/files/pylintrc
salt/reboot/infra.sls
salt/reboot/install_restart.sls
salt/reboot/restart_services.sls
salt/reboot/templates/pnda-restart.conf.tpl
salt/reboot/templates/properties.json.tpl
salt/top.sls

Provide two salt states: one that reboot the instances and one that restarts the PNDA services afterwards. These will be manually run by an operator to ensure the instances are fully up to date following package installation during provisioning.
PNDA-2250

Provide tools that allow pnda infra to be rebooted

---

salt/cdh/templates/cfg_pico.py.tpl

The CDH default had changed to 4GB which is too big for pico.
PNDA-2431

Reduce impala catalog server heap size for pico

---

pillar/flavors/pico.sls
pillar/flavors/standard.sls
salt/curator/init.sls

Keep 1 day of ES data for pico, standard stays at 6 days. Using flavor
specific pillar config to do this.
PNDA-2435

Reduce ES data retention for pico

---

salt/cdh/templates/cfg_standard.py.tpl

Collocating hbase master service with the hbase gw service to allow
anti-affinity group definition.
This depends on the new flavor definitions in https://github.com/pndaproject/pnda-heat-templates/blob/PNDA-2380/templates/standard/instance_flavors.yaml

Aggregating redundant services into common VM's.

---

salt/cdh/cloudera-manager.sls
salt/cdh/oozie_mysql.sls

Cloudera manager uses the external mqsql database already in use for
oozie, hue and hive instead of the embedded postgres database.
PNDA-2496

Cloudera manager uses external mqsql database

---

salt/cdh/files/cm_setup.py

Testing on constrained environments has shown
that during parcel distribution hosts can become
labelled in 'bad health', causing parcel distribution
to be errored. Eventually the hosts recover.

Give more time for parcels to distribute

---

salt/data-service/files/requirements.txt
salt/data-service/init.sls
salt/data-service/templates/data-service.conf.tpl

We use a requirements.txt file in salt because data-service does not
ship its own.

Use virtualenv for data service

---

salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_standard.py.tpl

Now application packages are in hdfs instead of hbase the cells don't
need to allow large values anymore
PNDA-2498

HBase values normal size again

---

salt/openstack/init.sls

We don't use openstack with salt anymore.

Remove unused sls file

---

salt/orchestrate/pnda-expand.sls
salt/orchestrate/pnda.sls

Increase the salt timeout in orchestrate runners so salt does not
proceed with next step too soon if the status poll times out.
PNDA-2494

Add timeouts in orchestrate runners

---

CHANGELOG.md
salt/cdh/files/cm_setup.py

If the previous run of cm_setup for cluster creation did not succeed then try again on subsequent runs of cm_setup, continuing from where it ran to last time. This will allow failed setup attempts to be retried.
The progress is recorded in ~/.CM_SETUP_SUCCESS. To override which bits are re-run edit this file otherwise it will continue where it reached up to last time. Once the initial cluster creation has succeeded the next time cm_setup runs it will expand the cluster or reapply config as normal rather than creating a new cluster..
PNDA-2517

Allow rerun of initial cluster creation by cm_setup

---

salt/cdh/files/cm_setup.py

Don't create hive temporary directory.
Seems like cloudera don't require anymore to create symlinks to
mysql_connector jar file.

Prune cm_setup to have only what is needed

---

CHANGELOG.md
salt/gobblin/templates/mr.pull.tpl

As this is an PNDA internal test topic, it's now not visible anymore
from a user point of view.

Prevent ingestion of the avro.internal.testbot topic

---

CHANGELOG.md
pillar/flavors/pico.sls
pillar/flavors/standard.sls
salt/kafka/server.sls
salt/kafka/templates/server.properties.tpl

Set kafka retention to 300MB for pico and 1GB for standard to avoid
disks filling up on pico.
PNDA-2680

Set kafka retention per flavor

---

salt/jupyter/templates/jupyterhub.service.tpl
salt/jupyter/templates/jupyterhub_config.py.tpl

Run jupyterhub as root the same as on ubuntu, not sure why it was being
run as hdfs in the redhat systemd unit.
PNDA-2704

Jupyter works on redhat

---

pillar/services.sls
salt/jupyter/jupyterhub.sls

Use new jupyter proxy upstream app instead of npm installing it from registry.
Depends on corresponding changes to pnda repository.
PNDA-2691

Handle Jupyter proxy as upstream app

---

salt/jmxproxy/init.sls

It prevents salt from changing ownership of /opt/pnda to root.

Move jmxproxy in its own directory

---

salt/elasticsearch-cluster/init.sls
salt/elasticsearch/init.sls
salt/kibana/init.sls
salt/logstash/init.sls

This prevent /opt/pnda to be chowned to root:root and chmoded to 777.

Don't enforce owner nor permissions, use the default

---

salt/cdh/files/cm_setup.py
salt/hdp/files/hdp_setup.py
salt/logserver/logshipper_templates/shipper.conf.tpl

cm_setup.py and hdp_setup.py both write to a log named hadoop_setup.py
to minimise differences.
PNDA-2967

Name hadoop setup log hadoop_setup.log

---

salt/deployment-manager/keys.sls
salt/jupyter/jupyter.sls

Assuming /home fails for users that don't have home directories in this location (root being the notable example)

Make safe use of os-user

---

salt/zookeeper/init.sls

Having the zookeeper-data-dir state setting the mode differently then
the subfile in the tree causes the state of my-id to change. This state
change causes the service to restart unnecessarily.

Change the mode of my-id file to match the tree mode state.

---

salt/jupyter/templates/pyspark_kernel.json.tpl

Remove asterisk from spark-examples.jar in PYSPARK_SUBMIT_ARGS in pyspark_kernel.json.tpl
PNDA-3233

Remove asterisk from spark-examples.jar

---

salt/master-dataset/init.sls

HDP setup in Ubuntu failed , Due to kite package key not found #279

Issue279: Fix HDP Kite Package Hashkey issue

---

pillar/packages/RedHat.sls

openssl 1.0.2 leaves ambari agents unable to connect to the server.
PNDA-3247

Fix openssl version at 1.0.1

---

salt/jupyter/files/requirements-jupyter.txt
salt/jupyter/jupyter_deps.sls

%sql is spark-sql magic of ipython kernel, which allows users to load data from relational database and impala using SQL as spark data-frames or pandas dataframes.
now sql magic is supported in all the three kernels, namely -
python3
python2 Anaconda
python pyspark

PNDA-2832- Jupyter %sql magic support.

---

CHANGELOG.md
salt/logserver/logserver.sls
salt/logserver/logshipper.sls

Link logstash install directory using the salt file.symlink command as
the cmd.run version was preventing logshipper/logserver upgrades
PNDA-3212

Link logstash install directory using salt file.symlink

---

salt/orchestrate/pnda-expand.sls
salt/orchestrate/pnda.sls
salt/reboot/kernel_reboot.sls

Problem Statement:
By default SaltStack not queuing job, need to enable  queue in all salt calls
Analysis:
Enable the beacon at any point of time one job would have been running i.e HIGH State or each of the Orchestrate states. After the beacon configuring, beacon run in the specified intervals (for milli seconds or so) . As per default salt state flow, only one job can run at any point of time.  Now if another job starts at the same time, the salt will not allow it. Now if we want salt jobs in parallel we need to specify a parameter called queue = True. By default it is False. 
Change:
The fix is needed to be in aws-template  <pnda-cli.py> and heat template for HIGH state and in pnda-salt orchestrate all the jobs to be added with this parameter. 
Test details:
Run deployment several …

Issue 290: Deployment failed due to saltstack

---

salt/_beacons/service_opentsdb.py
salt/_modules/pnda.py
salt/opentsdb/service.sls
salt/reactor/service_opentsdb_entry.sls

Problem Statement:
OpenTsdb service is not running after deployment
Analysis:
1. OpenTsdb service needs HBase service
2. if openTsdb started before HBase , it will down
3. PNDA-2389 restart the nodes after deployment, this cause the order of service placement
4. Need to start the OpenTsdb again after HBase is up
Change:
1. implement the Beacon and reactor method to implement fix
2. implement beacon only in OpenTsdb node only 
3. Check the Opentsdb status and Hbase status <ambari or cludera>
4. if OpenTsdb is Down and Habse is up, send the following tag to reactor 
+  - 'salt/beacon/*/service_opentsdb/service/opentsdb/status/stop/HBaseUp':
5. reactor will start the service again
Test details:
1. Need to test  all 16<2^4> combinations (OS,AWS),(HDP,CDH),(pico,standard),(redhat,ubuntu)
2. …

Issue293:OpenTsdb service not running after deployment

---

salt/_beacons/service_restart.py
salt/_modules/pnda.py
salt/_states/ambari_hadoop_restart.py
salt/hdp/service.sls
salt/reactor/service_hadoop_start_entry.sls

**# Problem Statement:**
PNDA 2390: NDA restarts any services that need restarting when rebooted
**# Analysis:**
Hadoop services are down due to node reboot or other issues
Services once down needs user intervention to start services
Need to automate the start process
**# Change:**
Fix supports for Ambari (HDP distribution)
implement the Beacon and reactor method to implement the fix
**BEACON:**
Beacon verify the current status using REST API <http://10.0.1.246:8080/api/v1/clusters/jana/>
Verify the health report and if any node down, starts the service
**REACTOR:**
verify the retry count, if it's less than 3 starts the process
print name of the services changed the state with a hostname
**# Test details:**
Verified  the fix for AWS:
1. UBUNTU - PICO -HDP
2. UBUNTU - STD -HDP
3. RHEL - …

PNDA 2390: PNDA restarts any services that need restarting when rebooted

---

CHANGELOG.md
pillar/pnda.sls
salt/app-packages/files/app-packages-hdfs.txt
salt/app-packages/files/app-packages-requirements.txt
salt/app-packages/hdfs-sync.sls
salt/app-packages/init.sls
salt/app-packages/templates/sync.sh.tpl
salt/cdh/setup_hadoop.sls
salt/cdh/templates/cfg_bmstandard.py.tpl
salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_standard.py.tpl
salt/jupyter/jupyter.sls
salt/jupyter/templates/pyspark_kernel.json.tpl
salt/orchestrate/pnda.sls

Support for adding pyspark application dependencies to both
pyspark-shell and Jupyter and for both driver and executor
scoped resolution. 
New ops SLS hdfs-sync stages eggs to a configurable (pillar) location
in HDFS, from where they can be added for executors with addPyFile.
Meanwhile, main SLS sets up virtualenvs to act as repositories on the
edge and Jupyter nodes for driver dependencies (in YARN client mode). 
Dependencies lists are managed through two files, much like any other set
of dependencies in platform-salt.
This PR omits support for pyspark-shell in HDP (Jupyter is covered).
PNDA-2982

Support for adding pyspark application dependencies

---

pillar/identity.sls
pillar/top.sls
salt/identity/users.sls
salt/master-dataset/pnda_hdfs_user.sls
salt/top.sls

These will only be injected if the authentication is based on the
pam_unix mode.

Add developer and production users as default users of the platform.

---

salt/_modules/kernel_reboot.py
salt/hdp/files/hdp_setup.py
salt/hdp/httpfs.sls

Plus a couple of minor changes for HDP clusters:
- don't verify the hadoop-https deb package, this needs revisiting to fix properly with the package being authenticated.
- enable hdp_setup debug to try and capture a problem I saw once with hdp_setup not waiting for installation to complete before existing

Disable rebooting for HDP clusters until that works reliably

---

CHANGELOG.md
salt/cdh/files/cm_setup.py

CM_SETUP_SUCCESS was being written to ~/ which would change depending
on which user ran cm_setup. This is fixed to /opt/pnda so different
users can run cm_setup from run to run.
PNDA-3340

Write CM_SETUP_SUCCESS into a fixed directory

---

salt/hdp/files/hdp_setup.py

Wait for task count to be non zero in hdp_setup before considering a request to be finished.

Wait for task count to be non zero in hdp_setup

---

CHANGELOG.md
salt/cdh/files/cm_setup.py

When expanding a cluster include spark on yarn so that new datanodes
are given a spark gateway role.
PNDA-3343

When expanding cluster include spark on yarn service

---

salt/_modules/pnda.py

Problem Statement:
ISSUE 311: Thrift server not started, due to Capital cluster name
Analysis:
Salt targetting is case sensitive
Ambari rest API return hostname only in small character
Need to convert the hostname to proper case-sensitive name
following SLS not targetted <HDP.start_additional_roles.sls?, so Thrift and rest servers are not started
Change:
change require in pnda custom module file.
changes in following functions:
ambari_get_hosts_by_role
hbase_master_host

Fix for Thrift server not started , due to Capital cluster name

---

CHANGELOG.md
pillar/packages/RedHat.sls
pillar/packages/Ubuntu.sls
salt/jupyter/extensions.sls
salt/jupyter/files/requirements-jupyter.txt
salt/jupyter/jupyter.sls
salt/jupyter/templates/pyspark_kernel.json.tpl
salt/jupyter/templates/requirements-jupyter-extensions.txt.tpl

The jupyter extensions (like lxml, ipywidet, ...) need to be installed
on both the client side and the kernel side.
See documentation @:
- http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html
- https://pypi.python.org/pypi/jupyter-spark/0.3.0
Depends on the pull request in the pnda repo.

PNDA-3238: Add jupyter extensions to the kenel virtual environment.

---

CHANGELOG.md
salt/pnda/user.sls

This is due to selinux permissive setting not being persisted.
In Salt version 2015.8, selinux.mode is not persisted. So a
file.replace is being added to persist the mode.

PNDA-3432: Jupyter not launching after reboot.

---

CHANGELOG.md
salt/pnda/user.sls

Remove recursive chmod for user directory.
This recursive chmod is not idempotent and overwrites identity files
permissions (amongst other) stored in that directory.

PNDA-3350: Fix dm.pem permission post deployment highstate.

---

salt/hdp/templates/cfg_production.py.tpl

Please don't delete the branch, more tuning will
follow. This has been proven working this far on the
production mock cluster.

Set Hadoop heap sizes for production flavor

---

CHANGELOG.md
salt/cdh/templates/cfg_bmstandard.py.tpl
salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_production.py.tpl
salt/cdh/templates/cfg_standard.py.tpl

Problem Statement:
=================
PNDA-3013: Keystone passwords with illegal XML characters (such as &) cause Hadoop setup to fail.
Analysis:
=========
If keystone_password contains any special characters (>, <, &, or "), Hadoop setup will fail because, in jinja template, these special characters are escaped.
By default, jinja2 does not escape the special characters.
NOTE: The same issue will also cause setup to fail if special characters in keystone_username,keystone_tenant and region.
Solution:
========
Fix : Esacping of keystone_password, keystone_user, keystone_tenant and region by piping the variable through the |e filter.
Files Changed :
===============
salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_standard.py.tpl
salt/cdh/templates/cfg_bmstandard.py.tpl …

PNDA-3013 Fix for Keystone passwords with illegal XML characters 

---

salt/hdp/httpfs.sls

Original code here needs review but applying simple fix immediately as all Ubuntu based clusters are now failing
PNDA-3490

Put back skip_verify

---

CHANGELOG.md
pillar/flavors/pico.sls
pillar/flavors/production.sls
pillar/flavors/standard.sls
salt/cdh/setup_hadoop.sls
salt/cdh/templates/cfg_pico.py.tpl
salt/cdh/templates/cfg_production.py.tpl
salt/cdh/templates/cfg_standard.py.tpl
salt/hdp/setup_hadoop.sls
salt/hdp/templates/cfg_pico.py.tpl
salt/hdp/templates/cfg_production.py.tpl
salt/hdp/templates/cfg_standard.py.tpl

Add setting data_volumes_count in pillar/flavors/flavor.sls that can be
used to control how many data volumes are used by HDFS. The directory
names follow the pattern /data0/dn, /data1/dn ... /dataN/dn. N is
padded so the number of digits is always the same for all volumes e.g.
/data00 if there are more than 10 total volumes.
PNDA-3497

Specify number of volumes to use for HDFS in pillar

---

pillar/flavors/bmstandard.sls
pillar/flavors/distribution.sls
pillar/flavors/pico.sls
pillar/flavors/production.sls
pillar/flavors/standard.sls
pillar/services.sls
salt/cdh/templates/cfg_production.py.tpl
salt/elasticsearch/init.sls
salt/hdp/templates/cfg_production.py.tpl
salt/kafka-tool/init.sls
salt/kafka/settings.sls
salt/mysql/init.sls
salt/zookeeper/init.sls

Place data directories for all the main elements on mnt in production flavor:
- hadoop
- mysql
- zookeeper
- kafka
- elasticsearch
PNDA-3489

Place data directories on mnt in production flavor
