pndaproject/platform-salt

- salt/graphite/files/carbon.conf
- salt/graphite/files/graphite-api.ini
- salt/graphite/files/graphite-api.yaml
- salt/graphite/files/graphite-carbon
- salt/graphite/files/graphite.conf
- salt/graphite/files/local_settings.py
- salt/graphite/files/storage-schemas.conf
- salt/graphite/init.sls
- salt/top.sls
Supports capturing time series metrics in the console.
PNDA-820
> Added graphite formula to salt.

- salt/grafana/init.sls
- salt/grafana/templates/grafana-datasources-setup.sh.tpl
- salt/grafana/templates/grafana-user-setup.sh.tpl
Add an OpenTSDB data source in Grafana during PNDA installation
> PNDA-1958 grafana opentsdb datasource

- pillar/services.sls
- salt/opentsdb/init.sls
> Pnda 1485 upgrade opentsdb

- salt/grafana/init.sls
- salt/grafana/templates/grafana-datasources-setup.sh.tpl
This datasource will be used to display PNDA platform metrics in Grafana
dashboards.
PNDA-2010
> Add a PNDA Graphite datasource in Grafana

- pillar/services.sls
Also, set Gobblin to PNDA branch
PNDA-2013
> Set all component versions to develop

- pillar/services.sls
Bring Gobblin build in line with other repos
PNDA-2013
> Update Gobblin to version 'develop'

- salt/grafana/files/dashboards/PNDA Deployment Manager.json
- salt/grafana/files/dashboards/PNDA Hadoop.json
- salt/grafana/files/dashboards/PNDA Kafka Brokers.json
- salt/grafana/files/dashboards/PNDA.json
- salt/grafana/init.sls
- salt/grafana/templates/grafana-import-dashboards.sh.tpl
> Add default PNDA Grafana Dashboards

- salt/grafana/files/dashboards/PNDA Deployment Manager.json
- salt/grafana/files/dashboards/PNDA Hadoop.json
- salt/grafana/files/dashboards/PNDA Kafka Brokers.json
> Use 'avg' function for smartSummarize in Grafana Dashboards

- pillar/pnda.sls
- salt/cdh/impala-shell.sls
- salt/console-backend/data-logger.sls
- salt/console-backend/data-manager.sls
- salt/console-frontend/init.sls
- salt/data-service/init.sls
- salt/deployment-manager/init.sls
- salt/deployment-manager/keys.sls
- salt/hdfs-cleaner/init.sls
- salt/jmxproxy/init.sls
- salt/jupyter/init.sls
- salt/jupyter/templates/jupyterhub_config.py.tpl
- salt/kafka/init.sls
- salt/logserver/logserver.sls
- salt/logserver/logshipper.sls
- salt/package-repository/init.sls
- salt/pnda/user.sls
- salt/zookeeper/init.sls
> Make 'pnda' home directory configurable in pillars

- salt/orchestrate/pnda.sls
- salt/platform-testing/create_topic.sls
- salt/platform-testing/files/topic-check.sh
Using Kafka CLI instead of KM
PNDA-2005
> Alternative way of setting up topics for platform-testing

- salt/jupyter/jupyter_deps.sls
This reverts commit c79ffa73db75b2e68166456f6382fdfbd2a94bd7.
PNDA-2119
> Revert "Use Anaconda binaries full path"

- salt/grafana/files/dashboards/PNDA Deployment Manager.json
- salt/grafana/files/dashboards/PNDA Hadoop.json
- salt/grafana/files/dashboards/PNDA Kafka Brokers.json
Set the timerange to 'Last 6 hours' for every PNDA Grafana dashboards.
PNDA-2118
> Fix grafana dashboard

- salt/cdh/files/README.md
- salt/cdh/files/cm_setup.py
- salt/cdh/templates/cfg_standard.py.tpl
- salt/cdh/templates/cloudera_config.py.tpl
> Use pnda:flavor grain and rename flavour to flavor

- salt/gobblin/init.sls
- salt/gobblin/pnda_flavors.map
- salt/gobblin/templates/mr.pull.tpl
> Use a map.jinja like file to define flavors

- salt/cdh/templates/cfg_pico.py.tpl
> Update pico flavor to remove unexisting settings for a few services

- salt/cdh/templates/cfg_pico.py.tpl
- salt/cdh/templates/cfg_standard.py.tpl
- salt/logserver/logshipper_templates/shipper.conf.tpl
> Change impala-llama log directory

- pillar/pnda.sls
- salt/master-dataset/init.sls
> Change default user to pnda for bulk HDFS directory

- salt/cdh/templates/cfg_pico.py.tpl
- salt/cdh/templates/cfg_standard.py.tpl
> Set httpfs to log to /var/log/pnda

- CHANGELOG.md
- salt/gobblin/templates/mr.pull.tpl
> Fix empty source partition

- salt/cdh/templates/cfg_standard.py.tpl
> Set journalnode to log to var/log/pnda

- .gitignore
- salt/cdh/setup_hadoop.sls
- salt/package-repository/templates/pr-config.json.tpl
> Use different keys for application repo and archive s3 buckets

- CHANGELOG.md
- salt/hdfs-cleaner/templates/properties.json.tpl
The config file is wired up with the credentials it needs to create the
container in swift or s3.
PNDA-2284
> hdfs-cleaner creates the archive container it needs

- salt/console-backend/data-logger.sls
- salt/console-backend/data-manager.sls
- salt/console-frontend/init.sls
- salt/data-service/init.sls
- salt/deployment-manager/init.sls
- salt/gobblin/init.sls
- salt/hdfs-cleaner/init.sls
- salt/kafka-manager/init.sls
- salt/package-repository/init.sls
- salt/platform-testing/cdh.sls
- salt/platform-testing/general.sls
- salt/pnda/platform-libraries.sls
Taken in conjunction with the change to extract the build logic from Jenkinsfiles this enables a simplified overall PNDA build process
PNDA-1918
> Simplify component paths

- salt/cdh/templates/hue-user-setup.sh.tpl
Catch the User.DoesNotExist error and set exit code explicitly. Also
added some more debug output.
PNDA-2392
> Refactor hue user creation

- salt/cdh/files/cm_setup.py
- salt/cdh/templates/cloudera_config.py.tpl
Re-apply config mode runs when re-running cm_setup on the same set of nodes. Re-running cm_setup with new nodes will trigger an expansion as before.
PNDA-1812
> Add a re-apply config mode to cm_setup.

- salt/cdh/cloudera-manager.sls
- salt/cdh/files/cm_setup.py
- salt/cdh/templates/cfg_pico.py.tpl
- salt/jupyter/templates/pyspark_kernel.json.tpl
> Bump cloudera version to 5.9.0

- salt/curator/init.sls
> Pin version of ES curator and specify full path

- salt/platform-testing/cdh.sls
- salt/platform-testing/create_topic.sls
- salt/platform-testing/general.sls
- salt/platform-testing/templates/platform-testing-cdh-blackbox.conf.tpl
- salt/platform-testing/templates/platform-testing-cdh.conf.tpl
- salt/platform-testing/templates/platform-testing-general-dm-blackbox.conf.tpl
- salt/platform-testing/templates/platform-testing-general-kafka.conf.tpl
- salt/platform-testing/templates/platform-testing-general-zookeeper.conf.tpl
> Use a python virtualenv for platform-testing

- salt/cdh/templates/cfg_pico.py.tpl
And update corresponding attributes in line
PNDA-2488
> Increase map tasks to 512MB

- salt/cdh/templates/cfg_pico.py.tpl
We're seeing OOMs and then connection failures
PNDA-2487
> Increase HBase heaps for CDH5.9

- salt/cdh/templates/cfg_pico.py.tpl
> Adjust hbase, yarn and mapred to better fit pico

- salt/cdh/templates/cfg_pico.py.tpl
> Further increase heap available to HBase Thrift server

- salt/jupyter/extensions.sls
> Latest release of lxml doesn't compile on AMI

- CHANGELOG.md
- pillar/services.sls
- salt/cdh/files/cm_setup.py
Interim merge of changes for release back to develop
> Release 1.2.0

- salt/hdfs-cleaner/files/requirements.txt
- salt/hdfs-cleaner/init.sls
- salt/hdfs-cleaner/templates/hdfs-cleaner.conf.tpl
> Use python virtualenv for hdfs-cleaner

- salt/deployment-manager/init.sls
- salt/deployment-manager/templates/deployment-manager.conf.tpl
> Use a python virtualenv for the deployment manager

- salt/package-repository/init.sls
- salt/package-repository/templates/package-repository.conf.tpl
> Use virtualenv for package repository

- salt/python-pip/init.sls
- salt/python-pip/pip3.sls
> Install virtualenv from pip instead of sytem packaging

- salt/cdh/cloudera-manager.sls
> Make Cloudera Manager database creation idempotent

- salt/graphite/files/requirements.txt
- salt/graphite/init.sls
- salt/graphite/templates/graphite-api.ini
Also remove some unused packages and add salt requires.
> Use a python virtualenv for graphite

- salt/gobblin/init.sls
- salt/gobblin/templates/gobblin.conf.tpl
- salt/gobblin/user.sls
- salt/hdfs-cleaner/init.sls
- salt/hdfs-cleaner/templates/properties.json.tpl
- salt/top.sls
> Stop using a specific 'gobblin' user to run gobblin

- salt/console-backend/templates/backend_nodejs_app.service.tpl
- salt/data-service/templates/data-service.service.tpl
- salt/deployment-manager/templates/deployment-manager.service.tpl
- salt/elasticsearch/files/templates/elasticsearch.service.tpl
- salt/jmxproxy/templates/jmxproxy.service.tpl
- salt/jupyter/templates/jupyterhub.service.tpl
- salt/kafka-manager/templates/kafka-manager.service.tpl
- salt/kafka/templates/kafka.service.tpl
- salt/kibana/templates/kibana.service.tpl
- salt/logserver/logserver_templates/logstash.service.tpl
- salt/logserver/logshipper_templates/logstash.service.tpl
- salt/opentsdb/templates/opentsdb.service.tpl
- salt/package-repository/templates/package-repository.service.tpl
- salt/reboot/templates/pnda-restart.service.tpl
- salt/zookeeper/files/templates/zookeeper.service.tpl
> Restart systemd services on failure

- salt/cdh/impala-shell.sls
- salt/cdh/templates/impala-shell.tpl
> Set virtual env for impala-wrapper

- salt/cdh/templates/cfg_pico.py.tpl
- salt/cdh/templates/cfg_standard.py.tpl
Spark streaming jobs look for files on the datanodes that are installed
as part of being a gateway.
PNDA-2721
> Add spark gateway roles to datanodes

- salt/gobblin/templates/gobblin.service.tpl
> Fix systemd unit for gobblin

- salt/logserver/logshipper.sls
- salt/logserver/logshipper_templates/shipper.conf.tpl
Use the journald plugin to gather systemd logs
PNDA-2727
> Aggregate systemd service logs

- salt/kibana/files/configure-dashboard.sh
> Add a wait on elasticsearch running for kibana-dashboard

- salt/nodejs/init.sls
Npm installing npm approach incompatible with offline installation
PNDA-2691
> Install nodejs/npm from deb/rhel packages

- pillar/services.sls
- salt/console-backend/data-logger.sls
- salt/console-backend/data-manager.sls
- salt/console-backend/utils.sls
- salt/console-frontend/init.sls
- salt/top.sls
> Refactor for offline installation

- salt/cdh/impala-shell.sls
- salt/cdh/setup_hadoop.sls
- salt/curator/init.sls
- salt/data-service/init.sls
- salt/deployment-manager/init.sls
- salt/graphite/init.sls
- salt/hdfs-cleaner/init.sls
- salt/jupyter/extensions.sls
- salt/jupyter/jupyter.sls
- salt/jupyter/jupyter_deps.sls
- salt/jupyter/jupyterhub.sls
- salt/package-repository/init.sls
- salt/platform-testing/cdh.sls
- salt/platform-testing/general.sls
- salt/python-pip/init.sls
- salt/python-pip/pip3.sls
- salt/reboot/install_restart.sls
> Remove pypi default URL

- salt/cdh/setup_hadoop.sls
Now needed for Python source based installation
> Add libffi-dev for hadoop setup

- salt/jupyter/extensions.sls
- salt/jupyter/files/requirements-jupyter.txt
- salt/jupyter/jupyter_deps.sls
- salt/jupyter/templates/requirements-jupyter-extensions.txt.tpl
> Install ipywidgets with pip

- salt/grafana/init.sls
- salt/logserver/logshipper.sls
Download logstash plugins from mirror.
Fix grafana rpm package name.
PNDA-2781
> Fixes for redhat mirror usage

- salt/cdh/clean_up_sources.sls
- salt/cdh/cloudera-manager-agent.sls
- salt/cdh/files/cm_setup.py
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
> Install cloudera manager agents manually

- salt/java/init.sls
Use wget instead of curl which has been unreliable for this package.
PNDA-2446
> Download java with wget

- CHANGELOG.md
- salt/jupyter/init.sls
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
- salt/pnda/platform-libraries.sls
> Install platform library on CDH datanodes

- CHANGELOG.md
- salt/cdh/files/cm_setup.py
- salt/logserver/logshipper_templates/shipper.conf.tpl
> Write cm_setup log to /var/log/pnda

- salt/reboot/restart_services.sls
> Start Cloudera Manager as part of restart_services

- salt/console-backend/data-logger.sls
> Start redis server before client

- salt/logserver/logserver.sls
> Remove online URL for logstash

- salt/kibana/init.sls
This prevents whole /opt/pnda/* to be owned by kibana:kibana.
> Update Kibana extraction to fix permission issues

- salt/console-backend/data-manager.sls
- salt/console-backend/templates/backend_data_manager_conf.js.tpl
- salt/console-frontend/init.sls
Fix the whitelist to include:
the ip addresses and hostname of the host with the console frontend.
the correct port number as configured in pillars when defined and present.
> Fix issue with data-manager white-listing for CORS.

- salt/package-repository/init.sls
> Add gcc dependency for package-repository

- CHANGELOG.md
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
> Install correct snappy libraries for HUE to use

- CHANGELOG.md
- salt/package-repository/templates/pr-config.json.tpl
> Add auth_version to package repository sls

- CHANGELOG.md
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
- salt/console-backend/data-logger.sls
- salt/console-backend/data-manager.sls
- salt/console-backend/utils.sls
- salt/console-frontend/init.sls
- salt/nodejs/init.sls
> Install nodejs from tar.gz

- CHANGELOG.md
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
- salt/ambari/agent.sls
- salt/ambari/files/ambari-server-log4j.properties
- salt/ambari/server.sls
- salt/ambari/templates/ambari-agent.ini.tpl
- salt/ambari/templates/ambari-server.properties.tpl
> Ambari salt formula

- CHANGELOG.md
- salt/hdp/files/hdp_setup.py
- salt/hdp/setup_hadoop.sls
- salt/hdp/templates/hdp_config.py.tpl
- salt/orchestrate/pnda.sls
> Option to install HDP instead of CDH and outline of HDP sls

- CHANGELOG.md
- salt/hdp/files/hdp_setup.py
> Submit super simple blueprint to Ambari

- pillar/packages/RedHat.sls
- salt/ambari/agent.sls
> Add libtirpc-devel

- CHANGELOG.md
- salt/_modules/pnda.py
- salt/ambari/agent.sls
- salt/cdh/cloudera-manager-agent.sls
- salt/cdh/cloudera-manager.sls
- salt/cdh/templates/cloudera_config.py.tpl
- salt/cdh/templates/impala-shell.tpl
- salt/console-frontend/init.sls
- salt/console-frontend/templates/PNDA.json.tpl
- salt/data-service/templates/server.conf.tpl
- salt/deployment-manager/templates/dm-config.json.tpl
- salt/hdfs-cleaner/templates/properties.json.tpl
- salt/hdp/templates/hdp_config.py.tpl
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
- salt/platform-testing/cdh.sls
- salt/pnda/platform-libraries.sls
- salt/reboot/files/pnda_restart.py
- salt/reboot/templates/properties.json.tpl
> Rename cloudera role grains to hadoop

- salt/cdh/setup_hadoop.sls
- salt/cdh/templates/cloudera_config.py.tpl
- salt/hdp/setup_hadoop.sls
- salt/hdp/templates/hdp_config.py.tpl
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
- salt/top.sls
> Rename cloudera cm_setup role grains to hadoop

- salt/platform-testing/cdh.sls
- salt/platform-testing/templates/platform-testing-cdh-blackbox.conf.tpl
- salt/platform-testing/templates/platform-testing-cdh-blackbox.service.tpl
> Pass hadoop distro to hadoop blackbox test module

- salt/ambari/server.sls
- salt/hdp/files/hdp_setup.py
Install jdbc driver for falcon
> Attempt a manual start if blueprint does not create OK

- salt/_modules/pnda.py
- salt/gobblin/init.sls
- salt/hdp/files/hdp_setup.py
- salt/master-dataset/init.sls
> Make salt module to find namenode function work on hdp (non-HA)

- salt/master-dataset/init.sls
> Install kite-dataset for HDP

- salt/platform-testing/cdh.sls
- salt/platform-testing/templates/platform-testing-hdp.conf.tpl
- salt/platform-testing/templates/platform-testing-hdp.service.tpl
> Use HDP metrics test plugin for HDP clusters

- pillar/services.sls
- salt/_modules/pnda.py
- salt/deployment-manager/init.sls
- salt/deployment-manager/templates/dm-config.json.tpl
> Pass hadoop distro to deployment manager

- salt/_modules/pnda.py
- salt/pnda_opentsdb/conf.sls
> Add get_hosts_by_role helper function for HDP

- salt/jupyter/jupyter.sls
- salt/jupyter/templates/pyspark_kernel.json.tpl
> Update jupyter config for HDP

- pillar/packages/RedHat.sls
- salt/anaconda/init.sls
> Include dependencies for anaconda on RH

- salt/console-frontend/init.sls
- salt/console-frontend/templates/PNDA.json.tpl
> Set hadoop manager link for Ambari

- pillar/services.sls
- salt/data-service/init.sls
- salt/data-service/templates/server.conf.tpl
- salt/hdfs-cleaner/init.sls
- salt/hdfs-cleaner/templates/properties.json.tpl
> HDP extensions for data-service and hdfs-cleaner

- salt/gobblin/init.sls
- salt/gobblin/templates/gobblin.conf.tpl
- salt/gobblin/templates/gobblin.service.tpl
> Set hadoop home for gobblin for HDP/CDH

- salt/hdp/files/hdp_setup.py
- salt/hdp/files/oozie_libs.py
- salt/hdp/files/requirements-hdp_setup.txt
- salt/hdp/oozie_libs.sls
- salt/orchestrate/pnda.sls
> Create platform deployment library for oozie on HDP

- salt/pnda_opentsdb/conf.sls
For HDP set tsd.storage.hbase.zk_basedir = /hbase-unsecure
PNDA-3045
> Adapt OpenTSDB for HDP

- salt/hdfs-cleaner/init.sls
- salt/hdfs-cleaner/templates/properties.json.tpl
> Set hdfs-cleaner paths for HDP

- pillar/flavors/bmstandard.sls
- pillar/flavors/pico.sls
- pillar/flavors/standard.sls
- salt/cdh/files/cm_setup.py
- salt/hdp/files/hdp_setup.py
- salt/hdp/setup_hadoop.sls
- salt/hdp/templates/cfg_pico.py.tpl
- salt/hdp/templates/hdp_config.py.tpl
> Externalise flavor config for hdp_setup

- salt/cdh/templates/cfg_pico.py.tpl
- salt/hdp/files/hdp_setup.py
- salt/hdp/templates/cfg_pico.py.tpl
Set HDFS replication factor for HDP dynamically and also remove falcon
and knox from blueprint.
PNDA-3057
> Set HDFS replication factor for HDP dynamically

- salt/cdh/files/cm_setup.py
> Raise error message from cm_setup.py when a parcel fails to download

- salt/hdp/setup_hadoop.sls
- salt/hdp/templates/cfg_pico.py.tpl
> Pico config for all hadoop services

- salt/cdh/templates/cfg_standard.py.tpl
- salt/hdp/files/hdp_setup.py
- salt/hdp/setup_hadoop.sls
- salt/hdp/start_additional_roles.sls
- salt/hdp/templates/cfg_standard.py.tpl
> Standard config for all hadoop services

- salt/hdp/templates/cfg_pico.py.tpl
- salt/hdp/templates/cfg_standard.py.tpl
Set Maximum AM Resource to 1.0
PNDA-3070
> Configuration for capacity-scheduler

- salt/cdh/templates/cfg_standard.py.tpl
> Add hdfs gateway role to CM host

- salt/jupyter/jupyterhub.sls
- salt/nodejs/init.sls
> Install nodejs to pnda homedir

- CHANGELOG.md
- salt/ntp/init.sls
> Set timezone to UTC via salt

- CHANGELOG.md
- salt/logserver/logserver_files/collector.conf
- salt/logserver/logshipper_templates/shipper.conf.tpl
> Multiline log messages from file input

- salt/graphite-api/files/storage-schemas.conf
Consistent time specification and fix regex
PNDA-3087
> Specify retention for PNDA metrics

- CHANGELOG.md
- salt/orchestrate/pnda.sls
- salt/top.sls
> Install CDH platform testing modules after CDH has been set up

- salt/cdh/create-yarn-home.sls
- salt/hdp/files/hdp_setup.py
> Create HDFS and Oozie ambari views

- CHANGELOG.md
- salt/gobblin/init.sls
Create log directory for gobblin which was missing and preventing log
from being written.
PNDA-3129
> Create gobblin log dir

- salt/anaconda/init.sls
- salt/hdp/files/hdp_setup.py
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
> Expand HDP clusters

- salt/hdp/files/hdp_setup.py
> Update config command for hdp clusters

- CHANGELOG.md
- salt/anaconda/init.sls
- salt/anaconda/templates/conda-cmd.tpl
- salt/cdh/anaconda.sls
- salt/top.sls
> Add conda command to PATH so it can be used out of the box

- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
> Update Ambari to 2.5.1.0

- salt/hdp/files/hdp_setup.py
> Add wait on Ambari API being up in hdp_setup.py

- pillar/services.sls
- salt/logserver/logshipper.sls
This resolves known issues with logstash-plugin install --local still trying to connect to Rubygems.
This requires PR https://github.com/pndaproject/pnda/pull/89
> Move to logstash 5.2.2 offline package install

- CHANGELOG.md
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
- pillar/services.sls
- salt/kafka-tool/init.sls
- salt/kafka-tool/templates/kafka-tool.conf.tpl
- salt/top.sls
PNDA-1960 - Make Kafkat available on nodes as option for Kafka management at CLI
> PNDA-1960 - Make Kafkat available on nodes as option for Kafka management at CLI

- CHANGELOG.md
- salt/orchestrate/pnda-expand.sls
- salt/orchestrate/pnda.sls
- salt/orchestrate/remove_new_node_marker.sls
> Target orchestrate operations at new nodes only

- CHANGELOG.md
- pillar/packages/RedHat.sls
> Use redis 3.2.10 on redhat

- CHANGELOG.md
- salt/opentsdb/hbase_tables.sls
> Report failures up if opentsdb.hbase_tables fails

- salt/jupyter/files/requirements-jupyter.txt
- salt/jupyter/jupyter_deps.sls
Reverts pndaproject/platform-salt#274
> Revert "PNDA-2832- Jupyter %sql magic support."

- CHANGELOG.md
- pillar/services.sls
- salt/cdh/cloudera-manager.sls
- salt/cdh/files/cm_setup.py
- salt/cdh/setup_hadoop.sls
> Externalise Cloudera CDH version

- CHANGELOG.md
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
- pillar/services.sls
- salt/cdh/cloudera-manager.sls
- salt/cdh/files/cm_setup.py
- salt/cdh/setup_hadoop.sls
Please merge https://github.com/pndaproject/platform-salt/pull/306 first as this work depends on that.
> Upgrade CDH and CM 5.12.1

- CHANGELOG.md
- pillar/flavors/production.sls
- salt/cdh/templates/cfg_production.py.tpl
Aimed at larger PNDA clusters
First version, before tuning
PNDA-3314
> Introduce new production flavor

- salt/cdh/templates/cfg_production.py.tpl
> Tuning for production flavor

- pillar/flavors/pico.sls
- pillar/flavors/production.sls
- pillar/flavors/standard.sls
- salt/kafka/server.sls
- salt/kafka/templates/kafka-env.tpl
- salt/kafka/templates/kafka.init.conf.tpl
- salt/opentsdb/files/opentsdb.default
- salt/opentsdb/init.sls
- salt/opentsdb/templates/opentsdb.default.tpl
- salt/opentsdb/templates/opentsdb.service.tpl
- salt/opentsdb/templates/opentsdb.start.tpl
- salt/pnda_opentsdb/conf.sls
- salt/zookeeper/files/templates/environment.tpl
- salt/zookeeper/init.sls
Makes heaps configurable via pillar and sets reasonable defaults
PNDA-3379
> Flavor based heap for Kafka, Zookeeper and OpenTSDB

- salt/top.sls
- salt/volumes/init.sls
> Create partitions and then format and mount volumes in salt

- CHANGELOG.md
- salt/logserver/logshipper_templates/shipper.conf.tpl
- salt/opentsdb/init.sls
- salt/opentsdb/templates/opentsdb_logback.xml.tpl
> Move opentsdb log to /var/log/pnda

- salt/volumes/init.sls
Wait for device link to appear before trying to use it
Fix for existing partitions and volume labels
PNDA-3181
> Fixes for volume mounting sls

- salt/hdp/templates/cfg_production.py.tpl
> Bug fix to metrics hbase heap

- salt/hdp/files/hdp_setup.py
An operator could choose to re-enable these once a system is shown to
be stable but these alerts are not helpful and are raised for otherwise
healthy clusters during the setup process.
PNDA-3245
> Disable stale alerts during provisioning

- salt/cdh/hue-login.sls
- salt/orchestrate/pnda.sls
Find out from Cloudera Manager where Hue is to avoid the need for a hue
grain.
PNDA-3452
> Remove use of hue grain

- salt/hdp/files/hdp_setup.py
When applying the blueprint, the monitoring function reports the status
in a loop. The report logs over and over again the same failure details
which ends up clogging the log report.
This change avoid duplicating those big reports but merely logs that
fact that the same task is still in failure state.
> Fix log overrun when applying the blueprint fails.

- salt/console-backend/data-logger.sls
- salt/console-backend/data-manager.sls
- salt/console-backend/utils.sls
- salt/console-frontend/init.sls
- salt/data-service/init.sls
- salt/deployment-manager/init.sls
- salt/elasticsearch-cluster/init.sls
- salt/gobblin/init.sls
- salt/hdfs-cleaner/init.sls
- salt/jupyter/jupyterhub.sls
- salt/kafka-tool/init.sls
- salt/logserver/logserver.sls
- salt/logserver/logshipper.sls
- salt/logstash/init.sls
- salt/package-repository/init.sls
- salt/platform-testing/cdh.sls
- salt/platform-testing/general.sls
- salt/zookeeper/init.sls
To reduce log output that clogs up the logs without being very useful.
PNDA-3517
> Remove verbose flag from tar commands

- CHANGELOG.md
- pillar/packages/CentOS.sls
- pillar/packages/RedHat.sls
- pillar/packages/Ubuntu.sls
- salt/ambari/agent.sls
- salt/ambari/server.sls
- salt/hdp/files/hdp_setup.py
> Ambari version 2.6.0.0 and HDP version 2.6.3.0

- salt/hdp/httpfs.sls
> Remove skip_verify on hadoop-httpfs install

- CHANGELOG.md
- salt/hdp/templates/cfg_pico.py.tpl
- salt/hdp/templates/cfg_production.py.tpl
- salt/hdp/templates/cfg_standard.py.tpl
> add support to Spark2 on HDP

- CHANGELOG.md
- salt/hdp/files/hdp_setup.py
> In hdp_setup only log tasks when their state changes

- CHANGELOG.md
- pillar/services.sls
> Zookeeper version 3.4.11

- CHANGELOG.md
- salt/hdfs-cleaner/init.sls
Previously this was limited to specific users, instead clean up the required files for all users.
PNDA-3323
> Clean up files for all users in hdfs_cleaner

- salt/hdp/files/oozie_libs.py
> Catch more errors in retry in oozie_libs.py
